services:
  webserver1:
    image: nginx
    ports:
      - "8080:80"
  webserver2:
    image: httpd
    ports:
      - "8081:80"
  WebapplicationLogin:
    image: web-application:1
    ports:
      - "8082:80"
  Ecommservice:
    image: ecommservice:1
    ports:
      - "8083:80"
  foodservice:
    image: nginx
    ports:
      - "8084:80"
    volumes:
      - /home/ubuntu/app_services/food:/usr/share/nginx/html
